version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  validation:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Execute mvn clean install
          command: mvn clean install

  sonar:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  analyse:
    jobs:
      - validation
      - sonar:
          filters:
            branches:
              only: develop
          context: SonarCloud
  build-and-deploy:
    jobs:
      - sonar:
          filters:
            branches:
              only: main
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: main
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only: main
          requires:
            - aws-ecr/build-and-push-image
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"