version: 2.1

jobs:
  validation:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Execute mvn clean install
          command: mvn clean install

  sonar:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  analyse:
    jobs:
      - validation
      - sonar:
          filters:
            branches:
              only: ["develop","main"]
          context: SonarCloud